routes/web.php
<?php

Route::get('/', 'PageController@home')->name('_root_');
Route::get('happy-home', 'PageController@home');


// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::get('change-password','DashboardController@changePassword')->name('change.password');
    Route::post('change-password','DashboardController@changePassword');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');
    Route::resource('galleries', 'GalleryController');
    Route::resource('socials', 'SocialController');
    Route::resource('admins', 'AdminController');
    Route::resource('registers', 'RegisterController');
    Route::resource('donates', 'DonateController');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::get('categories/showhide/{category}', 'CategoryController@showhide')->name('categories.showhide');
    Route::resource('units', 'UnitController');
    Route::resource('brands', 'BrandController');
    Route::resource('products', 'ProductController');
    Route::get('products/showhide/{product}', 'ProductController@showhide')->name('products.showhide');
    Route::resource('offers', 'OfferController');
});

Route::group(['middleware' => ['auth'], 'namespace' => 'User'], function () {
    Route::get('user', 'UserController@profile')->name('user.profile');
});

Auth::routes();

$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if ($page->slug == 'contact') {
        $router->get($page->slug, 'PageController@contact');
        $router->post($page->slug, 'PageController@contactmail')->name('contactmail');
    } elseif ($page->slug == 'reviews') {
        $router->get($page->slug, 'PageController@review');
    } elseif ($page->slug == 'join-with-us') {
        $router->get($page->slug, 'PageController@join');
        $router->post($page->slug, 'PageController@joinmail')->name('joinmail');
    } elseif ($page->slug != '/') {
        $router->get($page->slug, 'PageController@index');
    }
}


$cats = App\Category::all();
foreach ($cats as $page) {
    if($page->store_id == 2){
        $router->get('happy-home/'.$page->slug, 'CategoryController@index');        
    }else{
        $router->get($page->slug, 'CategoryController@index');
    }
}

Route::get(\App\Site::ID() . 'category/{category}', 'CategoryController@category')->name('category');
Route::get(\App\Site::ID() . 'category/{category}/{product}', 'CategoryController@product')->name('category.product');

Route::get('search', 'SearchController@index')->name('search');
Route::get('{category}/{product}', 'ProductController@product')->name('productdetails');

Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


Route::post('reviews', 'PageController@reviewsave')->name('review');


Route::get('donate', 'PageController@donate')->name('donate');
Route::post('donate', 'PageController@donate_save');
Route::get('donate/{donate}', 'PageController@donate_payment')->name('donate_payment');
Route::get('donate_paymentsuccess', 'PageController@donate_paymentsuccess')->name('donate_paymentsuccess');


Route::get('thankyou', 'PageController@thankyou')->name('thankyou');

//cart
Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


//Preview email on brower
Route::get('emailview/{id}', function ($id) {
    $tablebook = \App\Order::find($id);
    return new \App\Mail\NewOrder($tablebook);
});

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'dashboard') - {{ config('app.name', 'Laravel') }}</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('vendors/jquery-ui/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/linearicons/style.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/chartist/css/chartist-custom.css') }}">
    <link rel="stylesheet" href="{{ asset('backdo0r/css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('backdo0r/css/demo.css') }}">
</head>
<body>

    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href="{{ route('admin.dashboard') }}">{{config('app.name')}}</a>
            </div>
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>
                <form class="navbar-form navbar-left">
                    <div class="input-group">
                        <input type="text" value="" class="form-control" placeholder="Search dashboard...">
                        <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
                    </div>
                </form>
                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('settings.index') }}"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ asset('') }}" class="img-circle" alt="Avatar"> <span></span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('admin.logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        <i class="lnr lnr-exit"></i> <span>Logout</span>
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li><a href="{{ route('admin.dashboard') }}" {!!(!request()->segment(2) ? 'class="active"' : null) !!} ><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
                        <li><a href="{{ route('pages.index') }}" {!!(request()->segment(2) == 'pages' ? 'class="active"' : null) !!}><i class="lnr lnr-file-empty"></i> <span>Pages</span></a></li>
                        <li><a href="{{ route('categories.index') }}" {!!(request()->segment(2) == 'categories' ? 'class="active"' : null) !!}><i class="lnr lnr-file-empty"></i> <span>Categories</span></a></li>
                        <li><a href="{{ route('brands.index') }}" {!!(request()->segment(2) == 'brands' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Brand Management</span></a></li>
                        <li><a href="{{ route('products.index') }}" {!!(request()->segment(2) == 'products' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Products</span></a></li>
                        <li><a href="{{ route('offers.index') }}" {!!(request()->segment(2) == 'offers' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Offers</span></a></li>
                        <li><a href="{{ route('slides.index') }}" {!!(request()->segment(2) == 'slides' ? 'class="active"' : null) !!}><i class="lnr lnr-picture"></i> <span>Slides</span></a></li>
                        <li><a href="{{ route('labels.index') }}" {!!(request()->segment(2) == 'labels' ? 'class="active"' : null) !!}><i class="lnr lnr-spell-check"></i> <span>Labels</span></a></li>
                        <li><a href="{{ route('reviews.index') }}" {!!(request()->segment(2) == 'reviews' ? 'class="active"' : null) !!}><i class="lnr lnr-bubble"></i> <span>Reviews</span></a></li>
                        <li><a href="{{ route('units.index') }}" {!!(request()->segment(2) == 'units' ? 'class="active"' : null) !!}><i class="lnr lnr-layers"></i> <span>Units</span></a></li>
                        {{-- <li><a href="{{ route('galleries.index') }}" {!!(request()->segment(2) == 'galleries' ? 'class="active"' : null) !!}><i class="lnr lnr-camera"></i> <span>Galleries</span></a></li> --}}
                        <li><a href="{{ route('socials.index') }}" {!!(request()->segment(2) == 'socials' ? 'class="active"' : null) !!}><i class="lnr lnr-link"></i> <span>Socials</span></a></li>
                        <li><a href="{{ route('admins.index') }}" {!!(request()->segment(2) == 'admins' ? 'class="active"' : null) !!}><i class="lnr lnr-user"></i> <span>Admins</span></a></li>
                        <li><a href="{{ route('registers.index') }}" {!!(request()->segment(2) == 'registers' ? 'class="active"' : null) !!}><i class="lnr lnr-users"></i> <span>Registers</span></a></li>
                        <li><a href="{{ route('donates.index') }}" {!!(request()->segment(2) == 'donates' ? 'class="active"' : null) !!}><i class="lnr lnr-diamond"></i> <span>Donates</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p>
                            {{ Session::get('success') }}
                        </p>
                    </div>
                    @endif
                    @if (Session::has('error'))
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p>
                            {{ Session::get(    'error') }}
                        </p>
                    </div>
                    @endif

                    <!-- OVERVIEW -->
                    @yield('content')
                    <!-- END OVERVIEW -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                {{-- <p class="copyright">&copy;  <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p> --}}
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->

    {{-- <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('admin') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::check())
                            <li><a href="{{ route('pages.index') }}">Pages</a></li>
                            <li><a href="{{ route('categories.index') }}">Categories</a></li>
                            <li><a href="{{ route('items.index') }}">Items</a></li>
                        
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('admin.logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            @if (Session::has('success'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>
                    {{ Session::get('success') }}
                </p>
            </div>
            @endif
            @if (Session::has('error'))
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>
                    {{ Session::get(    'error') }}
                </p>
            </div>
            @endif
            @yield('content')
        </div>
    </div> --}}

    <!-- Scripts -->
    <script src="{{ asset('vendors/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('vendors/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
    <script src="{{ asset('vendors/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('backdo0r/scripts/klorofil-common.js') }}"></script>
    {{-- <script src="//cdn.ckeditor.com/4.10.1/basic/ckeditor.js"></script> --}}
    <script src="//cdn.ckeditor.com/4.10.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'details' );
    </script>
    @yield('script')
</body>
</html>

resources/views/admin/app_old.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'dashboard') - {{ config('app.name', 'Laravel') }}</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('vendors/jquery-ui/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/linearicons/style.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/chartist/css/chartist-custom.css') }}">
    <link rel="stylesheet" href="{{ asset('backdo0r/css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('backdo0r/css/demo.css') }}">
</head>
<body>

    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href="{{ route('admin.dashboard') }}">{{config('app.name')}}</a>
            </div>
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>
                <form class="navbar-form navbar-left">
                    <div class="input-group">
                        <input type="text" value="" class="form-control" placeholder="Search dashboard...">
                        <span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
                    </div>
                </form>
                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ route('settings.index') }}"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ asset('') }}" class="img-circle" alt="Avatar"> <span></span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('admin.logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        <i class="lnr lnr-exit"></i> <span>Logout</span>
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li><a href="{{ route('admin.dashboard') }}" {!!(!request()->segment(2) ? 'class="active"' : null) !!} ><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
                        <li><a href="{{ route('pages.index') }}" {!!(request()->segment(2) == 'pages' ? 'class="active"' : null) !!}><i class="lnr lnr-file-empty"></i> <span>Pages</span></a></li>
                        <li><a href="{{ route('categories.index') }}" {!!(request()->segment(2) == 'categories' ? 'class="active"' : null) !!}><i class="lnr lnr-file-empty"></i> <span>Categories</span></a></li>
                        <li><a href="{{ route('brands.index') }}" {!!(request()->segment(2) == 'brands' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Brand Management</span></a></li>
                        <li><a href="{{ route('products.index') }}" {!!(request()->segment(2) == 'products' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Products</span></a></li>
                        <li><a href="{{ route('offers.index') }}" {!!(request()->segment(2) == 'offers' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Offers</span></a></li>
                        <li><a href="{{ route('slides.index') }}" {!!(request()->segment(2) == 'slides' ? 'class="active"' : null) !!}><i class="lnr lnr-picture"></i> <span>Slides</span></a></li>
                        <li><a href="{{ route('labels.index') }}" {!!(request()->segment(2) == 'labels' ? 'class="active"' : null) !!}><i class="lnr lnr-spell-check"></i> <span>Labels</span></a></li>
                        <li><a href="{{ route('reviews.index') }}" {!!(request()->segment(2) == 'reviews' ? 'class="active"' : null) !!}><i class="lnr lnr-bubble"></i> <span>Reviews</span></a></li>
                        <li><a href="{{ route('units.index') }}" {!!(request()->segment(2) == 'units' ? 'class="active"' : null) !!}><i class="lnr lnr-layers"></i> <span>Units</span></a></li>
                        {{-- <li><a href="{{ route('galleries.index') }}" {!!(request()->segment(2) == 'galleries' ? 'class="active"' : null) !!}><i class="lnr lnr-camera"></i> <span>Galleries</span></a></li> --}}
                        <li><a href="{{ route('socials.index') }}" {!!(request()->segment(2) == 'socials' ? 'class="active"' : null) !!}><i class="lnr lnr-link"></i> <span>Socials</span></a></li>
                        <li><a href="{{ route('admins.index') }}" {!!(request()->segment(2) == 'admins' ? 'class="active"' : null) !!}><i class="lnr lnr-user"></i> <span>Admins</span></a></li>
                        <li><a href="{{ route('registers.index') }}" {!!(request()->segment(2) == 'registers' ? 'class="active"' : null) !!}><i class="lnr lnr-users"></i> <span>Registers</span></a></li>
                        <li><a href="{{ route('donates.index') }}" {!!(request()->segment(2) == 'donates' ? 'class="active"' : null) !!}><i class="lnr lnr-diamond"></i> <span>Donates</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if (Session::has('success'))
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p>
                            {{ Session::get('success') }}
                        </p>
                    </div>
                    @endif
                    @if (Session::has('error'))
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <p>
                            {{ Session::get(    'error') }}
                        </p>
                    </div>
                    @endif

                    <!-- OVERVIEW -->
                    @yield('content')
                    <!-- END OVERVIEW -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                {{-- <p class="copyright">&copy;  <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p> --}}
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->

    {{-- <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('admin') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::check())
                            <li><a href="{{ route('pages.index') }}">Pages</a></li>
                            <li><a href="{{ route('categories.index') }}">Categories</a></li>
                            <li><a href="{{ route('items.index') }}">Items</a></li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('admin.logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            @if (Session::has('success'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>
                    {{ Session::get('success') }}
                </p>
            </div>
            @endif
            @if (Session::has('error'))
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>
                    {{ Session::get(    'error') }}
                </p>
            </div>
            @endif
            @yield('content')
        </div>
    </div> --}}

    <!-- Scripts -->
    <script src="{{ asset('vendors/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('vendors/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('vendors/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
    <script src="{{ asset('vendors/chartist/js/chartist.min.js') }}"></script>
    <script src="{{ asset('backdo0r/scripts/klorofil-common.js') }}"></script>
    {{-- <script src="//cdn.ckeditor.com/4.10.1/basic/ckeditor.js"></script> --}}
    <script src="//cdn.ckeditor.com/4.10.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'details' );
    </script>
    @yield('script')
</body>
</html>