routes/web.php
<?php

Route::get('/', 'PageController@home')->name('_root_');
Route::get('happy-home', 'PageController@home');


// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::get('change-password','DashboardController@changePassword')->name('change.password');
    Route::post('change-password','DashboardController@changePassword');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');
    Route::resource('galleries', 'GalleryController');
    Route::resource('socials', 'SocialController');
    Route::resource('admins', 'AdminController');
    Route::resource('registers', 'RegisterController');
    Route::resource('donates', 'DonateController');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::get('categories/showhide/{category}', 'CategoryController@showhide')->name('categories.showhide');
    Route::resource('units', 'UnitController');
    Route::resource('brands', 'BrandController');
    Route::resource('products', 'ProductController');
    Route::get('products/showhide/{product}', 'ProductController@showhide')->name('products.showhide');
    Route::resource('offers', 'OfferController');
});

Route::group(['middleware' => ['auth'], 'namespace' => 'User'], function () {
    Route::get('user', 'UserController@profile')->name('user.profile');
});

Auth::routes();

$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if ($page->slug == 'contact') {
        $router->get($page->slug, 'PageController@contact');
        $router->post($page->slug, 'PageController@contactmail')->name('contactmail');
    } elseif ($page->slug == 'reviews') {
        $router->get($page->slug, 'PageController@review');
    } elseif ($page->slug == 'join-with-us') {
        $router->get($page->slug, 'PageController@join');
        $router->post($page->slug, 'PageController@joinmail')->name('joinmail');
    } elseif ($page->slug != '/') {
        $router->get($page->slug, 'PageController@index');
    }
}


$cats = App\Category::all();
foreach ($cats as $page) {
    if($page->store_id == 2){
        $router->get('happy-home/'.$page->slug, 'CategoryController@index');        
    }else{
        $router->get($page->slug, 'CategoryController@index');
    }
}

Route::get(\App\Site::ID() . 'category/{category}', 'CategoryController@category')->name('category');
Route::get(\App\Site::ID() . 'category/{category}/{product}', 'CategoryController@product')->name('category.product');

Route::get('search', 'SearchController@index')->name('search');
Route::get('{category}/{product}', 'ProductController@product')->name('productdetails');

Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


Route::post('reviews', 'PageController@reviewsave')->name('review');


Route::get('donate', 'PageController@donate')->name('donate');
Route::post('donate', 'PageController@donate_save');
Route::get('donate/{donate}', 'PageController@donate_payment')->name('donate_payment');
Route::get('donate_paymentsuccess', 'PageController@donate_paymentsuccess')->name('donate_paymentsuccess');


Route::get('thankyou', 'PageController@thankyou')->name('thankyou');

//cart
Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


//Preview email on brower
Route::get('emailview/{id}', function ($id) {
    $tablebook = \App\Order::find($id);
    return new \App\Mail\NewOrder($tablebook);
});

app/Label.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Label extends Model
{
	public function scopeOfValue($query, $labelid)
	{
		$label = $query->where('labelid', $labelid)->first();
		return $label ? ($label->value ? $label->value : '&nbsp;') : $labelid;		
	}
}

app/Http/Controllers/Admin/LabelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Label;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LabelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $labels = Label::all();
        return view('admin.label.index', compact('labels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pages = ['global', 'home'];        
        return view('admin.label.create', compact('pages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'page' => 'required',            
            'labelid' => 'required|unique:labels'
        ]);

        $label = new Label;
        $label->page = $request->page;
        $label->labelid = $request->page.':'.$request->labelid;
        $label->value = $request->value;
        $label->save();

        return redirect()->route('labels.index')->with('success', 'Label added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Label  $label
     * @return \Illuminate\Http\Response
     */
    public function show(Label $label)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Label  $label
     * @return \Illuminate\Http\Response
     */
    public function edit(Label $label)
    {
        $pages = ['global', 'home']; 
        return view('admin.label.edit', compact('pages', 'label'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Label  $label
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Label $label)
    {
        $this->validate($request, [
            'labelid' => 'required',
            ]);

        $label->value = $request->value;
        $label->save();

        return redirect()->route('labels.index')->with('success', 'Label saved.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Label  $label
     * @return \Illuminate\Http\Response
     */
    public function destroy(Label $label)
    {
        if($label && $label->delete()){
            return redirect()->route('labels.index')->with('success', 'Label deleted.');
        }else{
            return redirect()->route('labels.index')->with('error', 'Error while deleting Label.');
        }
    }
}

resources/views/admin/label/create.blade.php
@extends('admin.app')

@section('title')
Add Label
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('labels.store') }}" accept-charset="utf-8" method="post">
		{!! csrf_field() !!}

		@include('admin.label.form')
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/label/edit.blade.php
@extends('admin.app')

@section('title')
Edit label
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('labels.update', $label->id) }}" accept-charset="utf-8" method="post">
		{{ method_field('PUT') }}
		{!! csrf_field() !!}

		@include('admin.label.form')
		
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/label/form.blade.php
@if (!isset($label))
<div class="form-group">
	<label class="col-sm-2 control-label" for="page">Page</label>
	<div class="col-sm-3">
		<select class="form-control" name="page" id="page">
			<option value="">Select Page</option>			
			@foreach ($pages as $page)				
			<option value="{{ $page }}">{{ $page }}</option>			
			@endforeach
		</select>
	</div>
</div>
@endif

<div class="form-group">
	<label class="col-sm-2 control-label" for="labelid">Label Id</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="label Id" name="labelid" value="{{ old('labelid', isset($label) ? $label->labelid : null) }}" type="text" id="labelid" {{ isset($label) ? 'readonly="readonly"' : null }}>
	</div>
</div>


<div class="form-group">
	<label class="col-sm-2 control-label" for="value">Value</label>
	<div class="col-sm-8">
		<textarea rows="5" class="form-control" placeholder="Value" name="value" id="value">{{ old('value', isset($label) ? $label->value : null) }}</textarea>
	</div>
</div>

resources/views/admin/label/index.blade.php
@extends('admin.app')

@section('title')
Labels
@endsection

@section('content')

<div class="add-new">
	<a href="{{ route('labels.create') }}" class="btn btn-primary"><i class="lnr lnr-plus-circle"></i> <span>Add New</span></a>
</div>

<div class="content-table">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Page</th>
				<th>Label Id</th>
				<th>Value</th>
				<th>Created At</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($labels as $label)				
			<tr>
				<td>{{ $label->page }}</td>
				<td>{{ $label->labelid }}</td>
				<td>{{ $label->value }}</td>
				<td>{{ $label->created_at->format('M d, Y') }}</td>
				<td class="text-right">
					
						<a class="btn btn-primary btn-sm" href="{{ route('labels.edit', $label->id) }}"><i class="lnr lnr-pencil"></i></a>

						<div class="pull-right" style="margin-left: 10px;"> 
							<form onsubmit="return confirm('Are you sure?')" action="{{ route('labels.destroy', $label->id) }}" method="post">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}		
								<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
							</form>
						</div>
				</td>
			</tr>			
			@endforeach
		</tbody>
	</table>
</div>
@endsection