routes/web.php
<?php

Route::get('/', 'PageController@home')->name('_root_');
Route::get('happy-home', 'PageController@home');


// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function () {
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::get('change-password','DashboardController@changePassword')->name('change.password');
    Route::post('change-password','DashboardController@changePassword');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');
    Route::resource('galleries', 'GalleryController');
    Route::resource('socials', 'SocialController');
    Route::resource('admins', 'AdminController');
    Route::resource('registers', 'RegisterController');
    Route::resource('donates', 'DonateController');
    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::get('categories/showhide/{category}', 'CategoryController@showhide')->name('categories.showhide');
    Route::resource('units', 'UnitController');
    Route::resource('brands', 'BrandController');
    Route::resource('products', 'ProductController');
    Route::get('products/showhide/{product}', 'ProductController@showhide')->name('products.showhide');
    Route::resource('offers', 'OfferController');
});

Route::group(['middleware' => ['auth'], 'namespace' => 'User'], function () {
    Route::get('user', 'UserController@profile')->name('user.profile');
});

Auth::routes();

$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if ($page->slug == 'contact') {
        $router->get($page->slug, 'PageController@contact');
        $router->post($page->slug, 'PageController@contactmail')->name('contactmail');
    } elseif ($page->slug == 'reviews') {
        $router->get($page->slug, 'PageController@review');
    } elseif ($page->slug == 'join-with-us') {
        $router->get($page->slug, 'PageController@join');
        $router->post($page->slug, 'PageController@joinmail')->name('joinmail');
    } elseif ($page->slug != '/') {
        $router->get($page->slug, 'PageController@index');
    }
}


$cats = App\Category::all();
foreach ($cats as $page) {
    if($page->store_id == 2){
        $router->get('happy-home/'.$page->slug, 'CategoryController@index');        
    }else{
        $router->get($page->slug, 'CategoryController@index');
    }
}

Route::get(\App\Site::ID() . 'category/{category}', 'CategoryController@category')->name('category');
Route::get(\App\Site::ID() . 'category/{category}/{product}', 'CategoryController@product')->name('category.product');

Route::get('search', 'SearchController@index')->name('search');
Route::get('{category}/{product}', 'ProductController@product')->name('productdetails');

Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


Route::post('reviews', 'PageController@reviewsave')->name('review');


Route::get('donate', 'PageController@donate')->name('donate');
Route::post('donate', 'PageController@donate_save');
Route::get('donate/{donate}', 'PageController@donate_payment')->name('donate_payment');
Route::get('donate_paymentsuccess', 'PageController@donate_paymentsuccess')->name('donate_paymentsuccess');


Route::get('thankyou', 'PageController@thankyou')->name('thankyou');

//cart
Route::post('addtocart', 'CartController@addtocart')->name('addtocart');


//Preview email on brower
Route::get('emailview/{id}', function ($id) {
    $tablebook = \App\Order::find($id);
    return new \App\Mail\NewOrder($tablebook);
});

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
	public function scopeOfValue($query, $title)
	{
		$setting = $query->where('title', $title)->first();
		return $setting ? ($setting->value ? $setting->value : '&nbsp;') : $title;
	}
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Setting::all();
        return view('admin.setting.index', compact('settings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.setting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|unique:settings',
            'value' => 'required'
        ]);

        $setting = new Setting;
        $setting->title = $request->title;
        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('settings.index')->with('success', 'Setting added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        return view('admin.setting.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $this->validate($request, [
            'value' => 'required'
        ]);

        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('settings.index')->with('success', 'Setting saved.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        if($setting && $setting->delete()){
            return redirect()->route('settings.index')->with('success', 'Setting deleted.');
        }else{
            return redirect()->route('settings.index')->with('error', 'Error while deleting Setting.');
        }
    }
}

resources/views/admin/setting/create.blade.php
@extends('admin.app')

@section('title')
Add setting
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('settings.store') }}" accept-charset="utf-8" method="post">
		{!! csrf_field() !!}

		@include('admin.setting.form')
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('admin.app')

@section('title')
Edit setting
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('settings.update', $setting->id) }}" accept-charset="utf-8" method="post">
		{{ method_field('PUT') }}
		{!! csrf_field() !!}

		@include('admin.setting.form')
		
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/setting/form.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label" for="title">Title</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Title" name="title" value="{{ old('title', isset($setting) ? $setting->title : null) }}" type="text" id="title" {{ isset($setting) ? 'readonly="readonly"' : null }}>
	</div>
</div>


<div class="form-group">
	<label class="col-sm-2 control-label" for="value">Value</label>
	<div class="col-sm-8">
		<textarea rows="5" class="form-control" placeholder="Value" name="value" id="value">{{ old('value', isset($setting) ? $setting->value : null) }}</textarea>
	</div>
</div>

resources/views/admin/setting/index.blade.php
@extends('admin.app')

@section('title')
Settings
@endsection

@section('content')

<div class="add-new">
	<a href="{{ route('settings.create') }}" class="btn btn-primary"><i class="lnr lnr-plus-circle"></i> <span>Add New</span></a>
</div>

<div class="content-table">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Value</th>
				<th>Created At</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach ($settings as $setting)
			<tr>
				<td>{{ $setting->title }}</td>
				<td>{{ $setting->value }}</td>
				<td>{{ $setting->created_at->format('M d, Y') }}</td>
				<td class="text-right">
					
						<a class="btn btn-primary btn-sm" href="{{ route('settings.edit', $setting->id) }}"><i class="lnr lnr-pencil"></i></a>

						<div class="pull-right" style="margin-left: 10px;"> 
							<form onsubmit="return confirm('Are you sure?')" action="{{ route('settings.destroy', $setting->id) }}" method="post">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}		
								<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
							</form>
						</div>
				</td>
			</tr>			
			@endforeach
		</tbody>
	</table>
</div>
@endsection